import type { BINRange } from "@/types/card"

/**
 * COMPREHENSIVE CROATIAN BIN DATABASE
 * Updated with confirmed BINs from multiple sources
 */
export const CROATIAN_BIN_RANGES: BINRange[] = [
  // Zagrebačka banka (ZABA) - Croatia's largest bank
  {
    bin: "543778",
    binLength: 6,
    bank: "Zagrebačka banka",
    bankCode: "2360",
    cardType: "Mastercard",
    cardCategory: "Credit",
    cardLevel: "Standard",
    length: [16],
    country: "HR",
    currency: "EUR",
    isActive: true,
  },
  {
    bin: "464448",
    binLength: 6,
    bank: "Zagrebačka banka",
    bankCode: "2360",
    cardType: "Visa",
    cardCategory: "Credit",
    cardLevel: "Standard",
    length: [16],
    country: "HR",
    currency: "EUR",
    isActive: true,
  },
  {
    bin: "545616",
    binLength: 6,
    bank: "Zagrebačka banka",
    bankCode: "2360",
    cardType: "Mastercard",
    cardCategory: "Credit",
    cardLevel: "Standard",
    length: [16],
    country: "HR",
    currency: "EUR",
    isActive: true,
  },
  {
    bin: "527652",
    binLength: 6,
    bank: "Zagrebačka banka",
    bankCode: "2360",
    cardType: "Mastercard",
    cardCategory: "Debit",
    cardLevel: "Standard",
    length: [16],
    country: "HR",
    currency: "EUR",
    isActive: true,
  },
  {
    bin: "415948",
    binLength: 6,
    bank: "Zagrebačka banka",
    bankCode: "2360",
    cardType: "Visa",
    cardCategory: "Credit",
    cardLevel: "Classic",
    length: [16],
    country: "HR",
    currency: "EUR",
    isActive: true,
  },
  {
    bin: "414709",
    binLength: 6,
    bank: "Zagrebačka banka",
    bankCode: "2360",
    cardType: "Visa",
    cardCategory: "Debit",
    cardLevel: "Electron",
    length: [16],
    country: "HR",
    currency: "EUR",
    isActive: true,
  },

  // OTP Bank Croatia
  {
    bin: "547973",
    binLength: 6,
    bank: "OTP banka Hrvatska",
    bankCode: "2484",
    cardType: "Mastercard",
    cardCategory: "Credit",
    cardLevel: "Business",
    length: [16],
    country: "HR",
    currency: "EUR",
    isActive: true,
  },
  {
    bin: "543357",
    binLength: 6,
    bank: "OTP banka Hrvatska",
    bankCode: "2484",
    cardType: "Mastercard",
    cardCategory: "Credit",
    cardLevel: "Standard",
    length: [16],
    country: "HR",
    currency: "EUR",
    isActive: true,
  },
  {
    bin: "516874",
    binLength: 6,
    bank: "OTP banka Hrvatska",
    bankCode: "2484",
    cardType: "Mastercard",
    cardCategory: "Debit",
    cardLevel: "Standard",
    length: [16],
    country: "HR",
    currency: "EUR",
    isActive: true,
  },
  {
    bin: "465847",
    binLength: 6,
    bank: "OTP banka Hrvatska",
    bankCode: "2484",
    cardType: "Visa",
    cardCategory: "Credit",
    cardLevel: "Classic",
    length: [16],
    country: "HR",
    currency: "EUR",
    isActive: true,
  },

  // Podravska banka
  {
    bin: "403877",
    binLength: 6,
    bank: "Podravska banka",
    bankCode: "2350",
    cardType: "Visa",
    cardCategory: "Credit",
    cardLevel: "Classic",
    length: [16],
    country: "HR",
    currency: "EUR",
    isActive: true,
  },

  // Privredna banka Zagreb (PBZ)
  {
    bin: "426733",
    binLength: 6,
    bank: "Privredna banka Zagreb",
    bankCode: "2340",
    cardType: "Visa",
    cardCategory: "Debit",
    cardLevel: "Traditional",
    length: [16],
    country: "HR",
    currency: "EUR",
    isActive: true,
  },
  {
    bin: "518906",
    binLength: 6,
    bank: "Privredna banka Zagreb",
    bankCode: "2340",
    cardType: "Mastercard",
    cardCategory: "Credit",
    cardLevel: "Standard",
    length: [16],
    country: "HR",
    currency: "EUR",
    isActive: true,
  },
  {
    bin: "528739",
    binLength: 6,
    bank: "Privredna banka Zagreb",
    bankCode: "2340",
    cardType: "Mastercard",
    cardCategory: "Debit",
    cardLevel: "Standard",
    length: [16],
    country: "HR",
    currency: "EUR",
    isActive: true,
  },
  {
    bin: "476259",
    binLength: 6,
    bank: "Privredna banka Zagreb",
    bankCode: "2340",
    cardType: "Visa",
    cardCategory: "Credit",
    cardLevel: "Classic",
    length: [16],
    country: "HR",
    currency: "EUR",
    isActive: true,
  },

  // Erste & Steiermärkische Bank (Erste Bank Croatia)
  {
    bin: "540667",
    binLength: 6,
    bank: "Erste & Steiermärkische Bank",
    bankCode: "2402",
    cardType: "Mastercard",
    cardCategory: "Credit",
    cardLevel: "Standard",
    length: [16],
    country: "HR",
    currency: "EUR",
    isActive: true,
  },
  {
    bin: "528264",
    binLength: 6,
    bank: "Erste & Steiermärkische Bank",
    bankCode: "2402",
    cardType: "Mastercard",
    cardCategory: "Debit",
    cardLevel: "Standard",
    length: [16],
    country: "HR",
    currency: "EUR",
    isActive: true,
  },
  {
    bin: "428417",
    binLength: 6,
    bank: "Erste & Steiermärkische Bank",
    bankCode: "2402",
    cardType: "Visa",
    cardCategory: "Credit",
    cardLevel: "Classic",
    length: [16],
    country: "HR",
    currency: "EUR",
    isActive: true,
  },

  // Raiffeisenbank Austria Croatia
  {
    bin: "548273",
    binLength: 6,
    bank: "Raiffeisenbank Austria Croatia",
    bankCode: "2390",
    cardType: "Mastercard",
    cardCategory: "Credit",
    cardLevel: "Standard",
    length: [16],
    country: "HR",
    currency: "EUR",
    isActive: true,
  },
  {
    bin: "524681",
    binLength: 6,
    bank: "Raiffeisenbank Austria Croatia",
    bankCode: "2390",
    cardType: "Mastercard",
    cardCategory: "Debit",
    cardLevel: "Standard",
    length: [16],
    country: "HR",
    currency: "EUR",
    isActive: true,
  },

  // Societe Generale - Splitska banka
  {
    bin: "527385",
    binLength: 6,
    bank: "Societe Generale - Splitska banka",
    bankCode: "2340",
    cardType: "Mastercard",
    cardCategory: "Credit",
    cardLevel: "Standard",
    length: [16],
    country: "HR",
    currency: "EUR",
    isActive: true,
  },

  // Hrvatska poštanska banka
  {
    bin: "532874",
    binLength: 6,
    bank: "Hrvatska poštanska banka",
    bankCode: "2500",
    cardType: "Mastercard",
    cardCategory: "Credit",
    cardLevel: "Standard",
    length: [16],
    country: "HR",
    currency: "EUR",
    isActive: true,
  },

  // Addiko Bank Croatia (formerly Hypo Alpe Adria)
  {
    bin: "547293",
    binLength: 6,
    bank: "Addiko Bank Croatia",
    bankCode: "2409",
    cardType: "Mastercard",
    cardCategory: "Credit",
    cardLevel: "Standard",
    length: [16],
    country: "HR",
    currency: "EUR",
    isActive: true,
  },

  // Revolut (Digital bank)
  {
    bin: "537462",
    binLength: 6,
    bank: "Revolut",
    cardType: "Mastercard",
    cardCategory: "Prepaid",
    cardLevel: "Standard",
    length: [16],
    country: "HR",
    currency: "EUR",
    isActive: true,
  },

  // International cards
  {
    bin: "374859",
    binLength: 6,
    bank: "American Express Croatia",
    cardType: "American Express",
    cardCategory: "Credit",
    cardLevel: "Green",
    length: [15],
    country: "HR",
    currency: "EUR",
    isActive: true,
  },
  {
    bin: "305729",
    binLength: 6,
    bank: "Diners Club Croatia",
    cardType: "Diners Club",
    cardCategory: "Credit",
    cardLevel: "Classic",
    length: [14],
    country: "HR",
    currency: "EUR",
    isActive: true,
  },

  // Inactive banks
  {
    bin: "478594",
    binLength: 6,
    bank: "Sberbank Croatia",
    bankCode: "2478",
    cardType: "Visa",
    cardCategory: "Credit",
    cardLevel: "Classic",
    length: [16],
    country: "HR",
    currency: "EUR",
    isActive: false,
  },
]
